# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Compiler/GNU-C.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Compiler/GNU-CXX.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU-C.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU-CXX.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/Platform/UnixPaths.cmake\
/Users/songqi/Documents/SVN/MyDevelop/Engine/extlibs/IosLibs/freetype/CMakeFiles/CMakeCCompiler.cmake\
/Users/songqi/Documents/SVN/MyDevelop/Engine/extlibs/IosLibs/freetype/CMakeFiles/CMakeCXXCompiler.cmake\
/Users/songqi/Documents/SVN/MyDevelop/Engine/extlibs/IosLibs/freetype/CMakeFiles/CMakeSystem.cmake\
/Users/songqi/Documents/SVN/MyDevelop/Engine/extlibs/IosLibs/freetype/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/songqi/Documents/SVN/MyDevelop/Engine/extlibs/IosLibs/freetype -B/Users/songqi/Documents/SVN/MyDevelop/Engine/extlibs/IosLibs/freetype
